- name: dockerリポジトリを追加
  get_url:
    url: "https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }}/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo

- name: dockerのインストール
  yum:
    name: docker-ce
    state: present

- name: ユーザをdockerグループに追加
  user:
    name: kkano
    groups: docker
    append: yes

- name: dockerを有効化
  systemd:
    name: docker
    state: started
    enabled: yes

- name: docker-composeのURLを解析
  shell:
    "curl --silent --show-error https://api.github.com/repos/docker/compose/releases/latest | grep '{{ ansible_system | lower }}-{{ ansible_architecture }}\"' | grep browser_download_url | cut --delimiter='\"' --fields=4"
  args:
    warn: no
  register:
    docker_compose_url

- name: docker-composeのインストール
  get_url:
    url: "{{ docker_compose_url.stdout }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: aliasを設定
  blockinfile:
    path:
      "~{{item}}/.bashrc"
    block: |
      alias dc='docker-compose'
    marker:
      "# {mark} Insert by docker install playbook"
  with_items:
    - root
    - kkano
