- name: create data directories
  file:
    path: "{{item}}"
    state: directory
    owner: "10001"
  with_items:
    - /storage/mssql/data
    - /storage/mssql/log
    - /storage/mssql/secrets

- name: copy docker-compose.yml
  copy:
    src: roles/mssql/files/docker-compose.yml
    dest: /app/mssql/

- name: docker-compose up
  docker_compose:
    project_src: /app/mssql/
